api_user:
    resource: "@FrancoinBundle/Controller/UserController.php"
    type:     rest

api_region:
    resource: "@FrancoinBundle/Controller/RegionController.php"
    type:     rest

api_post:
    resource: "@FrancoinBundle/Controller/PostController.php"
    type:     rest

api_image:
    resource: "@FrancoinBundle/Controller/ImageController.php"
    type:     rest

api_favourite:
    resource: "@FrancoinBundle/Controller/FavouriteController.php"
    type:     rest

api_comment:
    resource: "@FrancoinBundle/Controller/CommentController.php"
    type:     rest

api_city:
    resource: "@FrancoinBundle/Controller/CityController.php"
    type:     rest

api_category:
    resource: "@FrancoinBundle/Controller/CategoryController.php"
    type:     rest

api_attribute:
    resource: "@FrancoinBundle/Controller/AttributeController.php"
    type:     rest